"""Path + dataset-loading helpers.

Each dataset module is loaded from its file under an explicit unique module name via
importlib (`load_py`), never by a bare `import`. That keeps KWS, SVA and LM data able to
coexist in one process -- `theory/degenerate_tokens.py` needs all three -- and makes every
driver independent of import order.

ensure_paths() adds only REPO_ROOT, which is all `oscillator_attention` and `training`
need; it deliberately adds nothing else.
"""
import importlib.util
import os
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def ensure_paths():
    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)
    return REPO_ROOT


def load_py(path, modname):
    """Load a .py file as a module under an explicit unique name (idempotent)."""
    if modname in sys.modules:
        return sys.modules[modname]
    spec = importlib.util.spec_from_file_location(modname, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[modname] = mod
    spec.loader.exec_module(mod)
    return mod


def load_kws_dataset():
    ensure_paths()
    return load_py(os.path.join(REPO_ROOT, "training", "kws_dataset.py"),
                   "kws_dataset_mod")


def load_sva_dataset():
    ensure_paths()
    return load_py(os.path.join(REPO_ROOT, "training", "sva_dataset.py"),
                   "sva_dataset_mod")


def results_root():
    """READ root: the reference results -- the run behind the paper, tracked in git.

    Override with OSCILLATOR_RESULTS to read a different tree; pointing it at ``runs``
    regenerates figures and analyses from your own run instead of ours."""
    return os.environ.get("OSCILLATOR_RESULTS", os.path.join(REPO_ROOT, "results"))


def runs_root():
    """WRITE root: where drivers put their output. Gitignored and absent on a clean
    clone, so a re-run lands beside the reference instead of over it. Override with
    OSCILLATOR_RUNS."""
    return os.environ.get("OSCILLATOR_RUNS", os.path.join(REPO_ROOT, "runs"))


def cache_root():
    """Root for downloaded corpora and regenerated checkpoints.

    Configure with the OSCILLATOR_DATA_CACHE environment variable; defaults to
    <repo>/data/cache. Populate corpora with data/fetch_data.py; checkpoints are
    regenerated by training (see README). No path outside the repo is used."""
    return os.environ.get("OSCILLATOR_DATA_CACHE",
                          os.path.join(REPO_ROOT, "data", "cache"))
